#ifndef MWEMU_H
#define MWEMU_H

#pragma once

/* Auto-generated by cbindgen from crates/mwemu-c. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// No access.
#define MWEMU_PERM_NONE 0

// Readable.
#define MWEMU_PERM_READ 1

// Writable.
#define MWEMU_PERM_WRITE 2

// Executable.
#define MWEMU_PERM_EXECUTE 4

// Read + write + execute (the default used when allocating).
#define MWEMU_PERM_RWX 7

// Opaque handle to an emulator instance. Treat as `void*`; never dereference.
typedef struct MwemuEmu MwemuEmu;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Return the last error message recorded on this thread, or NULL if none.
//
// The pointer is owned by the library and stays valid until the next call on
// the same thread; copy it if you need to keep it.
const char *mwemu_last_error(void);

// Create a 32-bit x86 emulator. Free with `mwemu_free_emu`.
struct MwemuEmu *mwemu_init32(void);

// Create a 64-bit x86-64 emulator. Free with `mwemu_free_emu`.
struct MwemuEmu *mwemu_init64(void);

// Create an AArch64 (ARM64) emulator. Free with `mwemu_free_emu`.
struct MwemuEmu *mwemu_init_aarch64(void);

// Destroy an emulator created by any `mwemu_init*` / load function.
void mwemu_free_emu(struct MwemuEmu *emu);

// Library version string. Free with `mwemu_free_string`.
char *mwemu_version(void);

// Rebuild an emulator from a serialized state blob (see `mwemu_serialize`).
// Returns NULL on a corrupt/invalid blob (check `mwemu_last_error`).
struct MwemuEmu *mwemu_deserialize(const uint8_t *data, uintptr_t len);

// Rebuild an emulator from a minidump file. Returns NULL on failure.
struct MwemuEmu *mwemu_load_from_minidump(const char *filename);

// Rebuild an emulator from a state file written by `mwemu_dump_to_file`.
struct MwemuEmu *mwemu_load_from_file(const char *filename);

// Rebuild an emulator from a state file written by `mwemu_dump`.
struct MwemuEmu *mwemu_load(const char *filename);

// Last emulated mnemonic with operands. Free with `mwemu_free_string`.
// Returns NULL if no instruction has been decoded yet.
char *mwemu_get_prev_mnemonic(struct MwemuEmu *emu);

// Reset the instruction counter to zero.
void mwemu_reset_pos(struct MwemuEmu *emu);

// 1 if the emulator is in 64-bit mode, 0 otherwise.
int32_t mwemu_is_64bits(struct MwemuEmu *emu);

// 1 if the emulator is in 32-bit mode, 0 otherwise.
int32_t mwemu_is_32bits(struct MwemuEmu *emu);

// Switch to 64-bit x86-64 mode (needs the matching maps folder).
void mwemu_set_64bits(struct MwemuEmu *emu);

// Switch to 32-bit x86 mode.
void mwemu_set_32bits(struct MwemuEmu *emu);

// Switch to AArch64 mode.
void mwemu_set_aarch64(struct MwemuEmu *emu);

// Change the LDR-entry base address of a loaded module.
void mwemu_update_ldr_entry_base(struct MwemuEmu *emu, const char *libname, uint64_t base);

// Resolve an API address to its name. Free with `mwemu_free_string`.
char *mwemu_api_addr_to_name(struct MwemuEmu *emu, uint64_t addr);

// Resolve an API name to its address (0 if not found).
uint64_t mwemu_api_name_to_addr(struct MwemuEmu *emu, const char *name);

// Disable colored output.
void mwemu_disable_colors(struct MwemuEmu *emu);

// Enable colored output.
void mwemu_enable_colors(struct MwemuEmu *emu);

// Trace all memory reads/writes.
void mwemu_enable_trace_mem(struct MwemuEmu *emu);

// Disable the memory tracer.
void mwemu_disable_trace_mem(struct MwemuEmu *emu);

// Trace all registers on every step.
void mwemu_enable_trace_regs(struct MwemuEmu *emu);

// Disable the register tracer.
void mwemu_disable_trace_regs(struct MwemuEmu *emu);

// Enable the loop counter (slower).
void mwemu_enable_count_loops(struct MwemuEmu *emu);

// Disable the loop counter.
void mwemu_disable_count_loops(struct MwemuEmu *emu);

// Allow emulating zero-filled code blocks.
void mwemu_allow_empty_code_blocks(struct MwemuEmu *emu);

// Enable shellcode mode.
void mwemu_enable_shellcode_mode(struct MwemuEmu *emu);

// Disable the memory inspector.
void mwemu_disable_inspect_sequence(struct MwemuEmu *emu);

// Enable the stack tracer.
void mwemu_enable_stack_trace(struct MwemuEmu *emu);

// Disable the stack tracer.
void mwemu_disable_stack_trace(struct MwemuEmu *emu);

// Enable test mode (cross-checks emulation against inline asm).
void mwemu_enable_test_mode(struct MwemuEmu *emu);

// Disable test mode.
void mwemu_disable_test_mode(struct MwemuEmu *emu);

// Enable the console.
void mwemu_enable_console(struct MwemuEmu *emu);

// Disable the console.
void mwemu_disable_console(struct MwemuEmu *emu);

// Trace a specific list of registers (array of lowercase names).
void mwemu_enable_trace_reg(struct MwemuEmu *emu, const char *const *names, uintptr_t count);

// Disable the multi-register tracer.
void mwemu_disable_trace_reg(struct MwemuEmu *emu);

// Set verbosity (0..=3).
void mwemu_set_verbose(struct MwemuEmu *emu, uint32_t verbose);

// Trace a NUL/length-delimited string at `addr` on every step.
void mwemu_enable_trace_string(struct MwemuEmu *emu, uint64_t addr);

// Disable the string tracer.
void mwemu_disable_trace_string(struct MwemuEmu *emu);

// Inspect a memory area described like `dword ptr [esp + 0x8]`.
void mwemu_enable_inspect_sequence(struct MwemuEmu *emu, const char *seq);

// Set the program entry point.
void mwemu_set_entry_point(struct MwemuEmu *emu, uint64_t addr);

// Rebase the code base address.
void mwemu_set_base_address(struct MwemuEmu *emu, uint64_t addr);

// Set the stack base address.
void mwemu_set_stack_base(struct MwemuEmu *emu, uint64_t addr);

// Keep emulating past unimplemented instructions/APIs (banzai mode).
void mwemu_enable_banzai_mode(struct MwemuEmu *emu);

// Disable banzai mode.
void mwemu_disable_banzai_mode(struct MwemuEmu *emu);

// Register an API name + parameter count for banzai mode.
void mwemu_banzai_add(struct MwemuEmu *emu, const char *apiname, int32_t nparams);

// Enable Ctrl-C handling (spawns the console).
void mwemu_enable_ctrlc(struct MwemuEmu *emu);

// Disable Ctrl-C handling.
void mwemu_disable_ctrlc(struct MwemuEmu *emu);

// Spawn the interactive console after `position` instructions.
void mwemu_spawn_console_at_pos(struct MwemuEmu *emu, uint64_t position);

// Spawn the interactive console when reaching `addr`.
void mwemu_spawn_console_at_addr(struct MwemuEmu *emu, uint64_t addr);

// Spawn the interactive console now.
void mwemu_spawn_console(struct MwemuEmu *emu);

// Set the maps folder (realistic memory layout from the mwemu maps repo).
void mwemu_load_maps(struct MwemuEmu *emu, const char *folder);

// Fetch genuine Windows system DLLs from the symbol server and use them as the
// maps folder. `version` is a friendly name ("win11") or a build ("26100.7920").
// Returns 1 on success, 0 on failure (network/cache; see `mwemu_last_error`).
int32_t mwemu_load_maps_from_winver(struct MwemuEmu *emu, const char *version);

// Initialize the Windows environment (PEB/TEB/LDR/DLLs) for 32-bit.
void mwemu_init_win32(struct MwemuEmu *emu);

// Initialize the Linux environment (optionally with dynamic linking).
void mwemu_init_linux64(struct MwemuEmu *emu, int32_t dynamic);

// Load a binary (PE/ELF/Mach-O or shellcode) from a file path.
void mwemu_load_binary(struct MwemuEmu *emu, const char *filename);

// Load shellcode from a raw byte buffer.
void mwemu_load_code_bytes(struct MwemuEmu *emu, const uint8_t *data, uintptr_t len);

// Allocate a named map of `size` bytes (RWX by default). Returns the base
// address through `out_addr`; 1 on success, 0 on error.
int32_t mwemu_alloc(struct MwemuEmu *emu,
                    const char *name,
                    uint64_t size,
                    uint8_t perm_bits,
                    uint64_t *out_addr);

// Allocate a named map at a fixed address. Returns 1 on success, 0 on error.
int32_t mwemu_alloc_at(struct MwemuEmu *emu,
                       const char *name,
                       uint64_t addr,
                       uint64_t size,
                       uint8_t perm_bits);

// Load an additional blob file at `base_addr` as a named map.
int32_t mwemu_load_map(struct MwemuEmu *emu,
                       const char *name,
                       const char *filename,
                       uint64_t base_addr);

// Link a library by path, returning its base address (0 on failure path).
uint64_t mwemu_link_library(struct MwemuEmu *emu, const char *filepath);

// Free a named memory map.
void mwemu_free(struct MwemuEmu *emu, const char *name);

// Read a register by name (e.g. "rax", "eip", "x0"). 1 on success, 0 on error.
int32_t mwemu_get_reg(struct MwemuEmu *emu, const char *reg, uint64_t *out);

// Set a register by name; writes the previous value to `out_prev` if non-NULL.
// Returns 1 on success, 0 on error.
int32_t mwemu_set_reg(struct MwemuEmu *emu, const char *reg, uint64_t value, uint64_t *out_prev);

// Read an XMM register by name into a lo/hi `uint64_t` pair (x86 only).
int32_t mwemu_get_xmm(struct MwemuEmu *emu, const char *reg, uint64_t *out_lo, uint64_t *out_hi);

// Set an XMM register from a lo/hi `uint64_t` pair (x86 only).
int32_t mwemu_set_xmm(struct MwemuEmu *emu, const char *reg, uint64_t lo, uint64_t hi);

// Get the program counter (any arch).
uint64_t mwemu_get_pc(struct MwemuEmu *emu);

// Set the program counter (any arch).
void mwemu_set_pc(struct MwemuEmu *emu, uint64_t addr);

// Get the stack pointer (any arch).
uint64_t mwemu_get_sp(struct MwemuEmu *emu);

// Set the stack pointer (any arch).
void mwemu_set_sp(struct MwemuEmu *emu, uint64_t addr);

// Set RIP; if it points to an API it will be emulated. Returns 1/0.
int32_t mwemu_set_rip(struct MwemuEmu *emu, uint64_t addr);

// Set EIP; if it points to an API it will be emulated. Returns 1/0.
int32_t mwemu_set_eip(struct MwemuEmu *emu, uint64_t addr);

// Number of instructions emulated so far.
uint64_t mwemu_get_position(struct MwemuEmu *emu);

// Push a 32-bit value. Returns 1 on success, 0 on error.
int32_t mwemu_stack_push32(struct MwemuEmu *emu, uint32_t value);

// Push a 64-bit value. Returns 1 on success, 0 on error.
int32_t mwemu_stack_push64(struct MwemuEmu *emu, uint64_t value);

// Pop a 32-bit value into `out`. Returns 1 on success, 0 on error.
int32_t mwemu_stack_pop32(struct MwemuEmu *emu, uint32_t *out);

// Pop a 64-bit value into `out`. Returns 1 on success, 0 on error.
int32_t mwemu_stack_pop64(struct MwemuEmu *emu, uint64_t *out);

// Stop emulation.
void mwemu_stop(struct MwemuEmu *emu);

// Emulate a single step. Returns 1 if it continued, 0 otherwise.
int32_t mwemu_step(struct MwemuEmu *emu);

// Run until `end_addr` (when `has_end` != 0) or forever. Writes the final PC
// to `out_pc`. Returns 1 on success, 0 on error (see `mwemu_last_error`).
int32_t mwemu_run(struct MwemuEmu *emu, int32_t has_end, uint64_t end_addr, uint64_t *out_pc);

// Run until reaching instruction-count `position`. Returns 1/0.
int32_t mwemu_run_to(struct MwemuEmu *emu, uint64_t position, uint64_t *out_pc);

// Run until the first return. Returns 1/0.
int32_t mwemu_run_until_return(struct MwemuEmu *emu, uint64_t *out_pc);

// Run until the next winapi call. Writes the API address to `out_addr` and its
// name to `out_name` (free with `mwemu_free_string`). Returns 1/0.
int32_t mwemu_run_until_apicall(struct MwemuEmu *emu, uint64_t *out_addr, char **out_name);

// Handle a winapi call at `addr`.
void mwemu_handle_winapi(struct MwemuEmu *emu, uint64_t addr);

// Call a 32-bit function, pushing `params` (reverse order internally).
// Writes the return value to `out_ret`. Returns 1/0.
int32_t mwemu_call32(struct MwemuEmu *emu,
                     uint64_t address,
                     const uint32_t *params,
                     uintptr_t nparams,
                     uint32_t *out_ret);

// Call a 64-bit (Windows ABI) function. Writes the return value to `out_ret`.
int32_t mwemu_call64(struct MwemuEmu *emu,
                     uint64_t address,
                     const uint64_t *params,
                     uintptr_t nparams,
                     uint64_t *out_ret);

// Call a 64-bit function using the Linux SysV ABI.
int32_t mwemu_linux_call64(struct MwemuEmu *emu,
                           uint64_t address,
                           const uint64_t *params,
                           uintptr_t nparams,
                           uint64_t *out_ret);

// Disassemble `amount` instructions at `addr`. Free with `mwemu_free_string`.
char *mwemu_disassemble(struct MwemuEmu *emu, uint64_t addr, uint32_t amount);

// Write a little-endian qword. Returns 1 on success, 0 if unmapped.
int32_t mwemu_write_qword(struct MwemuEmu *emu, uint64_t addr, uint64_t value);

// Write a little-endian dword. Returns 1 on success, 0 if unmapped.
int32_t mwemu_write_dword(struct MwemuEmu *emu, uint64_t addr, uint32_t value);

// Write a little-endian word. Returns 1 on success, 0 if unmapped.
int32_t mwemu_write_word(struct MwemuEmu *emu, uint64_t addr, uint16_t value);

// Write a byte. Returns 1 on success, 0 if unmapped.
int32_t mwemu_write_byte(struct MwemuEmu *emu, uint64_t addr, uint8_t value);

// Read a little-endian qword into `out`. Returns 1 on success, 0 if unmapped.
int32_t mwemu_read_qword(struct MwemuEmu *emu, uint64_t addr, uint64_t *out);

// Read a little-endian dword into `out`. Returns 1 on success, 0 if unmapped.
int32_t mwemu_read_dword(struct MwemuEmu *emu, uint64_t addr, uint32_t *out);

// Read a little-endian word into `out`. Returns 1 on success, 0 if unmapped.
int32_t mwemu_read_word(struct MwemuEmu *emu, uint64_t addr, uint16_t *out);

// Read a byte into `out`. Returns 1 on success, 0 if unmapped.
int32_t mwemu_read_byte(struct MwemuEmu *emu, uint64_t addr, uint8_t *out);

// Read a 128-bit little-endian value into a lo/hi pair. Returns 1/0.
int32_t mwemu_read_128bits_le(struct MwemuEmu *emu,
                              uint64_t addr,
                              uint64_t *out_lo,
                              uint64_t *out_hi);

// Read a 128-bit big-endian value into a lo/hi pair. Returns 1/0.
int32_t mwemu_read_128bits_be(struct MwemuEmu *emu,
                              uint64_t addr,
                              uint64_t *out_lo,
                              uint64_t *out_hi);

// Fill `amount` bytes at `addr` with `byte`.
void mwemu_memset(struct MwemuEmu *emu, uint64_t addr, uint8_t byte, uintptr_t amount);

// Write a byte buffer to memory.
void mwemu_write_buffer(struct MwemuEmu *emu, uint64_t addr, const uint8_t *data, uintptr_t len);

// Read `len` bytes from memory. Returns an owned buffer (free with
// `mwemu_free_buffer`) and writes its length to `out_len`.
uint8_t *mwemu_read_bytes(struct MwemuEmu *emu, uint64_t addr, uintptr_t len, uintptr_t *out_len);

// Read `len` bytes into a caller-provided buffer. Returns 1/0.
int32_t mwemu_read_mem(struct MwemuEmu *emu, uint64_t addr, uint8_t *out, uintptr_t len);

// Write a NUL-terminated ASCII string to memory.
void mwemu_write_string(struct MwemuEmu *emu, uint64_t addr, const char *s);

// Write a UTF-16 (wide) string to memory.
void mwemu_write_wide_string(struct MwemuEmu *emu, uint64_t addr, const char *s);

// Read an ASCII string from memory. Free with `mwemu_free_string`.
char *mwemu_read_string(struct MwemuEmu *emu, uint64_t addr);

// Read a wide (UTF-16) string from memory. Free with `mwemu_free_string`.
char *mwemu_read_wide_string(struct MwemuEmu *emu, uint64_t addr);

// Spaced-hex string of `sz` bytes at `addr`. Free with `mwemu_free_string`.
char *mwemu_read_string_of_bytes(struct MwemuEmu *emu, uint64_t addr, uintptr_t sz);

// Size in bytes of a wide string at the given pointer.
uintptr_t mwemu_sizeof_wide(struct MwemuEmu *emu, uint64_t ptr);

// Write spaced-hex bytes ("90 90 c3") to memory. Returns 1/0.
int32_t mwemu_write_spaced_bytes(struct MwemuEmu *emu, uint64_t addr, const char *spaced);

// Print all memory maps whose name matches `kw`.
void mwemu_print_maps_by_keyword(struct MwemuEmu *emu, const char *kw);

// Print all memory maps.
void mwemu_print_maps(struct MwemuEmu *emu);

// Base address of the map containing `addr`. Returns 1/0.
int32_t mwemu_get_addr_base(struct MwemuEmu *emu, uint64_t addr, uint64_t *out);

// 1 if `addr` is mapped, 0 otherwise.
int32_t mwemu_is_mapped(struct MwemuEmu *emu, uint64_t addr);

// Name of the map containing `addr`. Free with `mwemu_free_string`; NULL if
// the address is not allocated.
char *mwemu_get_addr_name(struct MwemuEmu *emu, uint64_t addr);

// Hex-dump the bytes at `addr`.
void mwemu_dump_memory(struct MwemuEmu *emu, uint64_t addr);

// Hex-dump `amount` bytes at `addr`.
void mwemu_dump_n(struct MwemuEmu *emu, uint64_t addr, uint64_t amount);

// Total allocated bytes.
uintptr_t mwemu_allocated_size(struct MwemuEmu *emu);

// 1 if a block of `sz` at `addr` overlaps another map.
int32_t mwemu_memory_overlaps(struct MwemuEmu *emu, uint64_t addr, uint64_t sz);

// Print all allocations made during emulation.
void mwemu_show_allocs(struct MwemuEmu *emu);

// Find a free block of `sz` bytes (does not allocate). Returns 1/0.
int32_t mwemu_memory_alloc(struct MwemuEmu *emu, uint64_t sz, uint64_t *out_addr);

// Save every allocation to files under `path`.
void mwemu_save_all_allocs(struct MwemuEmu *emu, const char *path);

// Save `size` bytes at `addr` to `filename`.
void mwemu_save(struct MwemuEmu *emu, uint64_t addr, uint64_t size, const char *filename);

// Run a memory consistency test. Returns 1/0.
int32_t mwemu_mem_test(struct MwemuEmu *emu);

// Search an ASCII substring in a named map. Returns an owned `uint64_t` array
// (free with `mwemu_free_u64_buffer`); `out_count` gets the match count.
uint64_t *mwemu_search_string(struct MwemuEmu *emu,
                              const char *kw,
                              const char *map_name,
                              uintptr_t *out_count);

// Search spaced-hex bytes in a named map. Returns an owned `uint64_t` array.
uint64_t *mwemu_search_spaced_bytes(struct MwemuEmu *emu,
                                    const char *sbs,
                                    const char *map_name,
                                    uintptr_t *out_count);

// Search spaced-hex bytes across all maps. Returns an owned `uint64_t` array.
uint64_t *mwemu_search_spaced_bytes_in_all(struct MwemuEmu *emu,
                                           const char *sbs,
                                           uintptr_t *out_count);

// Search spaced-hex bytes forward from `saddr`. Returns the address or 0.
uint64_t mwemu_search_spaced_bytes_from(struct MwemuEmu *emu, uint64_t saddr, const char *sbs);

// Search spaced-hex bytes backward from `saddr`. Returns the address or 0.
uint64_t mwemu_search_spaced_bytes_from_bw(struct MwemuEmu *emu, uint64_t saddr, const char *sbs);

// Search a byte buffer in a named map. Returns an owned `uint64_t` array.
uint64_t *mwemu_search_bytes(struct MwemuEmu *emu,
                             const uint8_t *data,
                             uintptr_t len,
                             const char *map_name,
                             uintptr_t *out_count);

// Print all breakpoints.
void mwemu_bp_show(struct MwemuEmu *emu);

// Clear all breakpoints.
void mwemu_bp_clear_all(struct MwemuEmu *emu);

// Set an address breakpoint.
void mwemu_bp_set_addr(struct MwemuEmu *emu, uint64_t addr);

// Set an instruction-count breakpoint.
void mwemu_bp_set_inst(struct MwemuEmu *emu, uint64_t ins);

// Set a memory-read breakpoint.
void mwemu_bp_set_mem_read(struct MwemuEmu *emu, uint64_t addr);

// Set a memory-write breakpoint.
void mwemu_bp_set_mem_write(struct MwemuEmu *emu, uint64_t addr);

// Get all address breakpoints. Owned `uint64_t` array; free with
// `mwemu_free_u64_buffer`.
uint64_t *mwemu_bp_get_addr(struct MwemuEmu *emu, uintptr_t *out_count);

// Get all instruction-count breakpoints.
uint64_t *mwemu_bp_get_inst(struct MwemuEmu *emu, uintptr_t *out_count);

// Get all memory-read breakpoints.
uint64_t *mwemu_bp_get_mem_read(struct MwemuEmu *emu, uintptr_t *out_count);

// Get all memory-write breakpoints.
uint64_t *mwemu_bp_get_mem_write(struct MwemuEmu *emu, uintptr_t *out_count);

// Get the call stack as a flat `[from0, to0, from1, to1, ...]` `uint64_t`
// array. `out_count` gets the number of frames (pairs). Free the array with
// `mwemu_free_u64_buffer` passing `out_count * 2` as the element count.
uint64_t *mwemu_get_call_stack(struct MwemuEmu *emu, uintptr_t *out_count);

// Enable or disable threading emulation.
void mwemu_enable_threading(struct MwemuEmu *emu, int32_t enable);

// Serialize the whole emulator state. Owned buffer (free with
// `mwemu_free_buffer`); `out_len` gets the length.
uint8_t *mwemu_serialize(struct MwemuEmu *emu, uintptr_t *out_len);

// Serialize the state to a file (load with `mwemu_load_from_file`).
void mwemu_dump_to_file(struct MwemuEmu *emu, const char *filename);

// Serialize the state to a minidump file (load with `mwemu_load_from_minidump`).
void mwemu_dump_to_minidump(struct MwemuEmu *emu, const char *filename);

// Serialize the state to a file (load with `mwemu_load`).
void mwemu_dump(struct MwemuEmu *emu, const char *filename);

// Set max instructions; `has_value` 0 clears the limit.
void mwemu_set_max_instructions(struct MwemuEmu *emu, int32_t has_value, uint64_t value);

// Get max instructions into `out`. Returns 1 if set, 0 if unlimited.
int32_t mwemu_get_max_instructions(struct MwemuEmu *emu, uint64_t *out);

// Set the timeout in seconds; `has_value` 0 clears it.
void mwemu_set_timeout_secs(struct MwemuEmu *emu, int32_t has_value, double secs);

// Get the timeout into `out`. Returns 1 if set, 0 otherwise.
int32_t mwemu_get_timeout_secs(struct MwemuEmu *emu, double *out);

// Set max faults; `has_value` 0 clears it.
void mwemu_set_max_faults(struct MwemuEmu *emu, int32_t has_value, uint32_t faults);

// Get max faults into `out`. Returns 1 if set, 0 otherwise.
int32_t mwemu_get_max_faults(struct MwemuEmu *emu, uint32_t *out);

// Get the exit position (instruction count at which to stop).
uint64_t mwemu_get_exit_position(struct MwemuEmu *emu);

// Set the exit position.
void mwemu_set_exit_position(struct MwemuEmu *emu, uint64_t value);

// Get the trace start position.
uint64_t mwemu_get_trace_start(struct MwemuEmu *emu);

// Set the trace start position.
void mwemu_set_trace_start(struct MwemuEmu *emu, uint64_t value);

// Get the minimum heap allocation size.
uint64_t mwemu_get_heap_alloc_min_size(struct MwemuEmu *emu);

// Set the minimum heap allocation size.
void mwemu_set_heap_alloc_min_size(struct MwemuEmu *emu, uint64_t value);

// Get dump-on-exit (1/0).
int32_t mwemu_get_dump_on_exit(struct MwemuEmu *emu);

// Set dump-on-exit.
void mwemu_set_dump_on_exit(struct MwemuEmu *emu, int32_t value);

// Get trace-calls (1/0).
int32_t mwemu_get_trace_calls(struct MwemuEmu *emu);

// Set trace-calls.
void mwemu_set_trace_calls(struct MwemuEmu *emu, int32_t value);

// Get winapi emulation (1/0).
int32_t mwemu_get_emulate_winapi(struct MwemuEmu *emu);

// Set winapi emulation.
void mwemu_set_emulate_winapi(struct MwemuEmu *emu, int32_t value);

// Get short-circuit-sleep (1/0).
int32_t mwemu_get_short_circuit_sleep(struct MwemuEmu *emu);

// Set short-circuit-sleep.
void mwemu_set_short_circuit_sleep(struct MwemuEmu *emu, int32_t value);

// Get soft heap-free (1/0).
int32_t mwemu_get_heap_free_soft(struct MwemuEmu *emu);

// Set soft heap-free.
void mwemu_set_heap_free_soft(struct MwemuEmu *emu, int32_t value);

// Get SSDT LdrInitializeThunk usage (1/0).
int32_t mwemu_get_ssdt_use_ldr_initialize_thunk(struct MwemuEmu *emu);

// Set SSDT LdrInitializeThunk usage.
void mwemu_set_ssdt_use_ldr_initialize_thunk(struct MwemuEmu *emu, int32_t value);

// Set trace flags on/off.
void mwemu_set_trace_flags(struct MwemuEmu *emu, int32_t value);

// Open the trace file configured via `mwemu_set_trace_filename`.
void mwemu_open_trace_file(struct MwemuEmu *emu);

// Get the module name. Free with `mwemu_free_string`.
char *mwemu_get_module_name(struct MwemuEmu *emu);

// Set the module name.
void mwemu_set_module_name(struct MwemuEmu *emu, const char *value);

// Get the exe name. Free with `mwemu_free_string`.
char *mwemu_get_exe_name(struct MwemuEmu *emu);

// Set the exe name.
void mwemu_set_exe_name(struct MwemuEmu *emu, const char *value);

// Get the user name. Free with `mwemu_free_string`.
char *mwemu_get_user_name(struct MwemuEmu *emu);

// Set the user name.
void mwemu_set_user_name(struct MwemuEmu *emu, const char *value);

// Get the temp path. Free with `mwemu_free_string`.
char *mwemu_get_temp_path(struct MwemuEmu *emu);

// Set the temp path.
void mwemu_set_temp_path(struct MwemuEmu *emu, const char *value);

// Get the current working directory path. Free with `mwemu_free_string`.
char *mwemu_get_cwd_path(struct MwemuEmu *emu);

// Set the current working directory path.
void mwemu_set_cwd_path(struct MwemuEmu *emu, const char *value);

// Get the Windows directory. Free with `mwemu_free_string`.
char *mwemu_get_windows_directory(struct MwemuEmu *emu);

// Set the Windows directory.
void mwemu_set_windows_directory(struct MwemuEmu *emu, const char *value);

// Get the System directory. Free with `mwemu_free_string`.
char *mwemu_get_system_directory(struct MwemuEmu *emu);

// Set the System directory.
void mwemu_set_system_directory(struct MwemuEmu *emu, const char *value);

// Set the host name.
void mwemu_set_host_name(struct MwemuEmu *emu, const char *value);

// Get the dump filename, or NULL if unset. Free with `mwemu_free_string`.
char *mwemu_get_dump_filename(struct MwemuEmu *emu);

// Set the dump filename; a NULL pointer clears it.
void mwemu_set_dump_filename(struct MwemuEmu *emu, const char *value);

// Get the trace filename, or NULL if unset. Free with `mwemu_free_string`.
char *mwemu_get_trace_filename(struct MwemuEmu *emu);

// Set the trace filename; a NULL pointer clears it.
void mwemu_set_trace_filename(struct MwemuEmu *emu, const char *value);

// Free a `char*` returned by this library.
void mwemu_free_string(char *s);

// Free a byte buffer returned by this library.
void mwemu_free_buffer(uint8_t *ptr, uintptr_t len);

// Free a `uint64_t` array returned by this library.
void mwemu_free_u64_buffer(uint64_t *ptr, uintptr_t count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MWEMU_H */
