# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Emu",
    "Permission",
    "deserialize",
    "init32",
    "init64",
    "load",
    "load_from_file",
    "load_from_minidump",
]

@typing.final
class Emu:
    @property
    def max_instructions(self) -> typing.Optional[builtins.int]: ...
    @max_instructions.setter
    def max_instructions(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def timeout_secs(self) -> typing.Optional[builtins.float]: ...
    @timeout_secs.setter
    def timeout_secs(self, value: typing.Optional[builtins.float]) -> None: ...
    @property
    def max_faults(self) -> typing.Optional[builtins.int]: ...
    @max_faults.setter
    def max_faults(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def exit_position(self) -> builtins.int: ...
    @exit_position.setter
    def exit_position(self, value: builtins.int) -> None: ...
    @property
    def dump_on_exit(self) -> builtins.bool: ...
    @dump_on_exit.setter
    def dump_on_exit(self, value: builtins.bool) -> None: ...
    @property
    def dump_filename(self) -> typing.Optional[builtins.str]: ...
    @dump_filename.setter
    def dump_filename(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def trace_filename(self) -> typing.Optional[builtins.str]: ...
    @trace_filename.setter
    def trace_filename(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def trace_start(self) -> builtins.int: ...
    @trace_start.setter
    def trace_start(self, value: builtins.int) -> None: ...
    @property
    def trace_calls(self) -> builtins.bool: ...
    @trace_calls.setter
    def trace_calls(self, value: builtins.bool) -> None: ...
    @property
    def module_name(self) -> builtins.str: ...
    @module_name.setter
    def module_name(self, value: builtins.str) -> None: ...
    @property
    def exe_name(self) -> builtins.str: ...
    @exe_name.setter
    def exe_name(self, value: builtins.str) -> None: ...
    @property
    def user_name(self) -> builtins.str: ...
    @user_name.setter
    def user_name(self, value: builtins.str) -> None: ...
    @property
    def temp_path(self) -> builtins.str: ...
    @temp_path.setter
    def temp_path(self, value: builtins.str) -> None: ...
    @property
    def cwd_path(self) -> builtins.str: ...
    @cwd_path.setter
    def cwd_path(self, value: builtins.str) -> None: ...
    @property
    def windows_directory(self) -> builtins.str: ...
    @windows_directory.setter
    def windows_directory(self, value: builtins.str) -> None: ...
    @property
    def system_directory(self) -> builtins.str: ...
    @system_directory.setter
    def system_directory(self, value: builtins.str) -> None: ...
    @property
    def emulate_winapi(self) -> builtins.bool: ...
    @emulate_winapi.setter
    def emulate_winapi(self, value: builtins.bool) -> None: ...
    @property
    def short_circuit_sleep(self) -> builtins.bool: ...
    @short_circuit_sleep.setter
    def short_circuit_sleep(self, value: builtins.bool) -> None: ...
    @property
    def heap_alloc_min_size(self) -> builtins.int: ...
    @heap_alloc_min_size.setter
    def heap_alloc_min_size(self, value: builtins.int) -> None: ...
    @property
    def heap_free_soft(self) -> builtins.bool: ...
    @heap_free_soft.setter
    def heap_free_soft(self, value: builtins.bool) -> None: ...
    @property
    def ssdt_use_ldr_initialize_thunk(self) -> builtins.bool: ...
    @ssdt_use_ldr_initialize_thunk.setter
    def ssdt_use_ldr_initialize_thunk(self, value: builtins.bool) -> None: ...
    @trace_flags.setter
    def trace_flags(self, value: builtins.bool) -> None: ...
    @host_name.setter
    def host_name(self, value: builtins.str) -> None: ...
    def version(self) -> builtins.str:
        r"""
        get pymwemu version.
        """
    def get_prev_mnemonic(self) -> builtins.str:
        r"""
        get last emulated mnemonic with name and parameters.
        """
    def reset_pos(self) -> None:
        r"""
        reset the instruction counter to zero.
        """
    def is_64bits(self) -> builtins.bool:
        r"""
        check if the emulator is in 64bits mode.
        """
    def is_32bits(self) -> builtins.bool:
        r"""
        check if the emulator is in 32bits mode.
        """
    def update_ldr_entry_base(self, libname: builtins.str, base: builtins.int) -> None:
        r"""
        change base address on ldr entry of a module
        """
    def set_64bits(self) -> None:
        r"""
        Set 64bits mode, it's necessary to load the 64bits maps with load_maps() method.
        Or better can use: emu = pymwemu.init64()
        """
    def set_32bits(self) -> None:
        r"""
        Set 32bits mode, it's necessary to load the 32bits maps with load_maps() method.
        Or better can use: emu = pymwemu.init32()
        """
    def disable_colors(self) -> None:
        r"""
        disable the colored mode for instructions, api calls and other logs.
        """
    def enable_colors(self) -> None:
        r"""
        enable the colored mode.
        """
    def enable_trace_mem(self) -> None:
        r"""
        trace all memory reads and writes.
        """
    def disable_trace_mem(self) -> None:
        r"""
        disable the memory tracer.
        """
    def enable_trace_regs(self) -> None:
        r"""
        trace all the registers printing them in every step.
        """
    def disable_trace_regs(self) -> None:
        r"""
        disable the register tracer.
        """
    def enable_trace_reg(self, regs: typing.Sequence[builtins.str]) -> None:
        r"""
        trace a specific list of registers, provide  array of strings with register names in lower case.
        """
    def disable_trace_reg(self) -> None:
        r"""
        disable the multi-register tracer.
        """
    def inspect_seq(self, s: builtins.str) -> None:
        r"""
        inspect sequence
        """
    def api_addr_to_name(self, addr: builtins.int) -> builtins.str:
        r"""
        address to api name
        """
    def api_name_to_addr(self, name: builtins.str) -> builtins.int:
        r"""
        api name to address
        """
    def set_verbose(self, verbose: builtins.int) -> None:
        r"""
        set the verbosity between 0 and 3.
        0: only show api calls.
        1: show api calls and some logs.
        2: show also instructions (slower).
        3: show every iteration of rep preffix.
        """
    def set_stack_base(self, addr: builtins.int) -> None:
        r"""
        Set the base address of stack memory map
        """
    def spawn_console_at_pos(self, position: builtins.int) -> None:
        r"""
        when the execution reached a specified amount of steps will spawn an interactive console.
        """
    def spawn_console_at_addr(self, addr: builtins.int) -> None:
        r"""
        when the execution reached a specified address will spawn an interactive console.
        """
    def disable_spawn_console_at_pos(self) -> None:
        r"""
        disable the console spawning.
        """
    def enable_console(self) -> None:
        r"""
        allow to enable the console if its needed.
        """
    def disable_console(self) -> None:
        r"""
        disable the console, to prevent to be spawned in some situations.
        """
    def enable_count_loops(self) -> None:
        r"""
        enable the loops counter, this feature slows down the emulation but count the iteration number.
        """
    def disable_count_loops(self) -> None:
        r"""
        disable the loops counting system.
        """
    def allow_empty_code_blocks(self) -> None:
        r"""
        Allow emulating zero-filled code blocks (disables the empty block detector).
        """
    def enable_trace_string(self, addr: builtins.int) -> None:
        r"""
        enable tracing a string on a specified memory address.
        """
    def disable_trace_string(self) -> None:
        r"""
        disable the string tracer.
        """
    def enable_inspect_sequence(self, seq: builtins.str) -> None:
        r"""
        inspect a memory area by providing a stirng like 'dword ptr [esp + 0x8]'
        """
    def enable_shellcode_mode(self) -> None: ...
    def disable_inspect_sequence(self) -> None:
        r"""
        disable the memory inspector.
        """
    def set_entry_point(self, addr: builtins.int) -> None:
        r"""
        change the default entry point.
        """
    def set_base_address(self, addr: builtins.int) -> None:
        r"""
        rebase the program address.
        """
    def enable_stack_trace(self) -> None:
        r"""
        enable the stack tracer.
        """
    def disable_stack_trace(self) -> None:
        r"""
        disable the stack tracer.
        """
    def enable_test_mode(self) -> None:
        r"""
        test mode use inline assembly to contrast the result of emulation and detect bugs.
        """
    def disable_test_mode(self) -> None:
        r"""
        disable the test mode.
        """
    def enable_banzai_mode(self) -> None:
        r"""
        Enable banzai mode. This mode keep emulating after finding unimplemented instructions or apis.
        """
    def disable_banzai_mode(self) -> None:
        r"""
        disable banzai mode.
        """
    def banzai_add(self, apiname: builtins.str, nparams: builtins.int) -> None:
        r"""
        Add API to banzai.
        """
    def enable_ctrlc(self) -> None:
        r"""
        enable the Control-C handling for spawning console.
        """
    def disable_ctrlc(self) -> None:
        r"""
        disable the Control-C handling.
        """
    def load_maps(self, folder: builtins.str) -> None:
        r"""
        It is necessary to load the 32bits or 64bits maps folder for having a realistic memory layout.
        The maps can be downloaded from the https://github.com/sha0coder/mwemu
        """
    def init_win32(self) -> None:
        r"""
        load_binary() already calls init_win32() if its PE or shellcode.
        if you dont use load_binary and need the windows simulation
        then call this to have peb/teb/ldr/dlls loaded.
        """
    def init_linux64(self, dynamic: builtins.bool) -> None:
        r"""
        load_binary() already calls init_linux64() if its ELF
        if you dont use load_binary and need the linux simulation
        then call this to have libc etc loaded.
        """
    def load_binary(self, filename: builtins.str) -> None:
        r"""
        Load the binary to be emulated.
        """
    def load_code_bytes(self, bytes: typing.Sequence[builtins.int]) -> None:
        r"""
        Load code from bytes
        """
    def alloc(self, name: builtins.str, size: builtins.int, permission: typing.Optional[Permission] = None) -> builtins.int:
        r"""
        allocate a buffer on the emulated process address space. (permission defaults to RWX)
        """
    def alloc_at(self, name: builtins.str, addr: builtins.int, size: builtins.int, permission: typing.Optional[Permission] = None) -> None:
        r"""
        allocate at specific address (permission defaults to RWX)
        """
    def load_map(self, name: builtins.str, filename: builtins.str, base_addr: builtins.int) -> None:
        r"""
        load an aditional blob to the memory layout.
        """
    def link_library(self, filepath: builtins.str) -> builtins.int:
        r"""
        link library
        """
    def stack_push32(self, value: builtins.int) -> builtins.bool:
        r"""
        push a 32bits value to the stack.
        """
    def stack_push64(self, value: builtins.int) -> builtins.bool:
        r"""
        push a 64bits value to the stack.
        """
    def stack_pop32(self) -> builtins.int:
        r"""
        pop a 32bits value from the stack.
        """
    def stack_pop64(self) -> builtins.int:
        r"""
        pop a 64bits value from the stack.
        """
    def set_pc(self, addr: builtins.int) -> None:
        r"""
        set program counter (works for any arch).
        """
    def get_pc(self) -> builtins.int:
        r"""
        get program counter (works for any arch).
        """
    def get_sp(self) -> builtins.int:
        r"""
        get stack pointer (works for any arch).
        """
    def set_sp(self, addr: builtins.int) -> None:
        r"""
        set stack pointer (works for any arch).
        """
    def set_rip(self, addr: builtins.int) -> builtins.bool:
        r"""
        set rip register, if rip point to an api will be emulated.
        """
    def set_eip(self, addr: builtins.int) -> builtins.bool:
        r"""
        set eip register, if eip point to an api will be emulated.
        """
    def spawn_console(self) -> None:
        r"""
        spawn an interactive console.
        """
    def disassemble(self, addr: builtins.int, amount: builtins.int) -> builtins.str:
        r"""
        disassemble an address.
        """
    def stop(self) -> None:
        r"""
        stop emulation
        """
    def run_until_return(self) -> builtins.int:
        r"""
        start emulating the binary after finding the first return.
        """
    def step(self) -> builtins.bool:
        r"""
        emulate a single step, this is slower than run(address) or run(0)
        """
    def run(self, end_addr: typing.Optional[builtins.int]) -> builtins.int:
        r"""
        Start emulating the binary until reach the provided end_addr.
        Use run() with no params for emulating forever. or call32/call64 for calling a function.
        """
    def run_to(self, position: builtins.int) -> builtins.int:
        r"""
        Emulate until reaching a specific instruction position (number of instructions).
        """
    def get_position(self) -> builtins.int:
        r"""
        read the number of instructions emulated since now.
        """
    def call32(self, address: builtins.int, params: typing.Sequence[builtins.int]) -> builtins.int:
        r"""
        call a 32bits function, internally pushes params in reverse order.
        """
    def call64(self, address: builtins.int, params: typing.Sequence[builtins.int]) -> builtins.int:
        r"""
        call a 64bits function, internally pushes params in reverse order.
        """
    def linux_call64(self, address: builtins.int, params: typing.Sequence[builtins.int]) -> builtins.int: ...
    def get_reg(self, reg: builtins.str) -> builtins.int:
        r"""
        read register value ie get_reg('rax') or get_reg('x0')
        """
    def set_reg(self, reg: builtins.str, value: builtins.int) -> builtins.int:
        r"""
        set register value ie  set_reg('rax', 0x123) or set_reg('x0', 0x123), returns previous value.
        """
    def get_xmm(self, reg: builtins.str) -> builtins.int:
        r"""
        get the value of a xmm register (x86 only).
        """
    def set_xmm(self, reg: builtins.str, value: builtins.int) -> builtins.int:
        r"""
        set a value to a xmm register (x86 only).
        """
    def write_qword(self, addr: builtins.int, value: builtins.int) -> builtins.bool:
        r"""
        write a little endian qword on memory.
        """
    def write_dword(self, addr: builtins.int, value: builtins.int) -> builtins.bool:
        r"""
        write a little endian dword on memory.
        """
    def write_word(self, addr: builtins.int, value: builtins.int) -> builtins.bool:
        r"""
        write a little endian word on memory.
        """
    def write_byte(self, addr: builtins.int, value: builtins.int) -> builtins.bool:
        r"""
        write a byte on memory.
        """
    def read_128bits_be(self, addr: builtins.int) -> builtins.int:
        r"""
        read 128bits big endian.
        """
    def read_128bits_le(self, addr: builtins.int) -> builtins.int:
        r"""
        read 128bits little endian.
        """
    def read_qword(self, addr: builtins.int) -> builtins.int:
        r"""
        read little endian qword.
        """
    def read_dword(self, addr: builtins.int) -> builtins.int:
        r"""
        read little endian dword.
        """
    def read_word(self, addr: builtins.int) -> builtins.int:
        r"""
        read little endian word.
        """
    def read_byte(self, addr: builtins.int) -> builtins.int:
        r"""
        read a byte from a memory address.
        """
    def memset(self, addr: builtins.int, byte: builtins.int, amount: builtins.int) -> None:
        r"""
        fill a memory chunk starting at `address`, with a specified `amount` of bytes defined in `byte`.
        """
    def sizeof_wide(self, unicode_str_ptr: builtins.int) -> builtins.int:
        r"""
        get the size of a wide string.
        """
    def write_string(self, to: builtins.int, _from: builtins.str) -> None:
        r"""
        write string on memory.
        """
    def write_wide_string(self, to: builtins.int, _from: builtins.str) -> None:
        r"""
        write a wide string on memory.
        """
    def write_buffer(self, to: builtins.int, _from: typing.Sequence[builtins.int]) -> None:
        r"""
        write a python list of int bytes to the emulator memory.
        """
    def read_buffer(self, _from: builtins.int, sz: builtins.int) -> builtins.list[builtins.int]:
        r"""
        read a buffer &from the emulator memory to a python list of int bytes.
        """
    def write_bytes(self, to: builtins.int, _from: typing.Sequence[builtins.int]) -> None:
        r"""
        write a python list of int bytes to the emulator memory.
        """
    def print_maps_by_keyword(self, kw: builtins.str) -> None:
        r"""
        print all the maps that match a substring of the keyword provided.
        """
    def print_maps(self) -> None:
        r"""
        print all the memory maps on the process address space.
        """
    def get_addr_base(self, addr: builtins.int) -> builtins.int:
        r"""
        get the base address of a given address. Will make an exception if it's invalid address.
        """
    def is_mapped(self, addr: builtins.int) -> builtins.bool:
        r"""
        this method checks if the given address is allocated or not.
        """
    def get_addr_name(self, addr: builtins.int) -> builtins.str:
        r"""
        get the memory map name where is the given address.
        Will cause an exception if the address is not allocated.
        """
    def dump_memory(self, addr: builtins.int) -> None:
        r"""
        visualize the bytes on the given address.
        """
    def dump_n(self, addr: builtins.int, amount: builtins.int) -> None:
        r"""
        visualize the `amount` of bytes provided on `address`.
        """
    def dump_qwords(self, addr: builtins.int, n: builtins.int) -> None:
        r"""
        visualize a number of qwords on given address.
        """
    def dump_dwords(self, addr: builtins.int, n: builtins.int) -> None:
        r"""
        visualize a number of dwords on a given address.
        """
    def read_bytes(self, addr: builtins.int, sz: builtins.int) -> builtins.list[builtins.int]:
        r"""
        read an amount of bytes from an address to a python object.
        """
    def read_string_of_bytes(self, addr: builtins.int, sz: builtins.int) -> builtins.str:
        r"""
        read an amount of bytes from an address to a string of spaced hexa bytes.
        """
    def read_string(self, addr: builtins.int) -> builtins.str:
        r"""
        read an ascii string from a memory address,
        if the address point to a non allocated zone string will be empty.
        """
    def read_wide_string(self, addr: builtins.int) -> builtins.str:
        r"""
        read a wide string from a memory address,
        if the address point to a non allocated zone string will be empty.
        """
    def search_string(self, kw: builtins.str, map_name: builtins.str) -> builtins.list[builtins.int]:
        r"""
        search a substring on a specific memory map name, it will return a list of matched addresses.
        if the string is not found, it will return an empty list.
        """
    def write_spaced_bytes(self, addr: builtins.int, spaced_hex_bytes: builtins.str) -> builtins.bool:
        r"""
        write on emulators memory a spaced hexa bytes
        """
    def search_spaced_bytes_from(self, saddr: builtins.int, sbs: builtins.str) -> builtins.int:
        r"""
        search one occurence of a spaced hex bytes from a specific address, will return zero if it's not found.
        """
    def search_spaced_bytes_from_bw(self, saddr: builtins.int, sbs: builtins.str) -> builtins.int:
        r"""
        search one occcurence of a spaced hex bytes from an especific address backward,
        will return zero if it's not found.
        """
    def search_spaced_bytes(self, sbs: builtins.str, map_name: builtins.str) -> builtins.list[builtins.int]:
        r"""
        search spaced hex bytes string on specific map using its map name,
        will return a list with the addresses found if there are matches,
        otherwise the list will be empty.
        """
    def search_spaced_bytes_in_all(self, sbs: builtins.str) -> builtins.list[builtins.int]:
        r"""
        search spaced hex bytes string on all the memory layout,
        will return a list with the addresses found if there are matches,
        otherwise the list will be empty.
        """
    def search_string_in_all(self, kw: builtins.str) -> None:
        r"""
        Search a substring in all the memory layout except on libs, will print the results.
        In the future will return a list with results instead of printing.
        """
    def search_bytes(self, bkw: typing.Sequence[builtins.int], map_name: builtins.str) -> builtins.list[builtins.int]:
        r"""
        search a bytes object on specific map, will return a list with matched addresses if there are any.
        """
    def allocated_size(self) -> builtins.int:
        r"""
        show the total allocated memory.
        """
    def memory_overlaps(self, addr: builtins.int, sz: builtins.int) -> builtins.bool:
        r"""
        show if there are memory blocks overlaping eachother.
        """
    def show_allocs(self) -> None:
        r"""
        show all the memory blocks allocated during the emulation.
        """
    def free(self, name: builtins.str) -> None:
        r"""
        free a memory map by its name
        """
    def memory_alloc(self, sz: builtins.int) -> builtins.int:
        r"""
        basic allocator, it looks for a free block of given size,
        it only returns the address if its possible, but dont really allocates,
        just find the address, you have to load to that address something.
        use alloc() method instead if possible.
        """
    def save_all_allocs(self, path: builtins.str) -> None:
        r"""
        Save all memory blocks allocated during emulation to disk.
        Provide a folder where every alloc will be a file.
        """
    def save(self, addr: builtins.int, size: builtins.int, filename: builtins.str) -> None:
        r"""
        save a chunk of memory to disk.
        """
    def mem_test(self) -> builtins.bool:
        r"""
        perform a memory test to see overlapps or other possible problems.
        """
    def bp_show(self) -> None:
        r"""
        breakpoints
        show breakpoints
        """
    def bp_clear_all(self) -> None:
        r"""
        clear all the breakpoints
        """
    def bp_set_addr(self, addr: builtins.int) -> None:
        r"""
        set breakpoint on an address
        """
    def bp_get_addr(self) -> builtins.list[builtins.int]:
        r"""
        get the current address breakpoint
        """
    def bp_set_inst(self, ins: builtins.int) -> None:
        r"""
        set breakpoint on a instruction counter
        """
    def bp_get_inst(self) -> builtins.list[builtins.int]:
        r"""
        get breakpoint on a instrunction counter
        """
    def bp_set_mem_read(self, addr: builtins.int) -> None:
        r"""
        set a memory breakpoint on read
        """
    def bp_get_mem_read(self) -> builtins.list[builtins.int]:
        r"""
        get the memory breakpoint on read
        """
    def bp_set_mem_write(self, addr: builtins.int) -> None:
        r"""
        set a memory breakpoint on write
        """
    def bp_get_mem_write(self) -> builtins.list[builtins.int]:
        r"""
        get the memory breakpoint on write
        """
    def handle_winapi(self, addr: builtins.int) -> None:
        r"""
        handle winapi address
        """
    def run_until_apicall(self) -> tuple[builtins.int, builtins.str]:
        r"""
        emulate until next winapi call
        """
    def serialize(self) -> builtins.list[builtins.int]:
        r"""
        serialize the whole emulator state to a bytes object, which can be saved to disk for example
        """
    def dump_to_file(self, filename: builtins.str) -> None:
        r"""
        serialize the whole emulator state to a file, which can be loaded later with deserialize_dump
        """
    def dump_to_minidump(self, filename: builtins.str) -> None:
        r"""
        serialize the whole emulator state to a minidump file, which can be loaded later with load_from_minidump
        """
    def dump(self, filename: builtins.str) -> None: ...
    def open_trace_file(self) -> None: ...
    def get_call_stack(self) -> builtins.list[tuple[builtins.int, builtins.int]]: ...
    def enable_threading(self, enable: builtins.bool) -> None: ...

@typing.final
class Permission:
    NONE: Permission = ...
    READ: Permission = ...
    WRITE: Permission = ...
    EXECUTE: Permission = ...
    READ_WRITE: Permission = ...
    READ_EXECUTE: Permission = ...
    WRITE_EXECUTE: Permission = ...
    READ_WRITE_EXECUTE: Permission = ...
    @property
    def bits(self) -> builtins.int: ...
    @property
    def can_read(self) -> builtins.bool: ...
    @property
    def can_write(self) -> builtins.bool: ...
    @property
    def is_accessible(self) -> builtins.bool: ...
    def __new__(cls, read: builtins.bool = False, write: builtins.bool = False, execute: builtins.bool = False) -> Permission: ...
    @staticmethod
    def from_bits(bits: builtins.int) -> Permission: ...
    def __or__(self, rhs: Permission) -> Permission: ...
    def __and__(self, rhs: Permission) -> Permission: ...
    def __xor__(self, rhs: Permission) -> Permission: ...
    def __invert__(self) -> Permission: ...
    def __richcmp__(self, other: Permission, op: int) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

def deserialize(data: typing.Sequence[builtins.int]) -> Emu:
    r"""
    deserialize the emulator state from a bytes object, which can be loaded from disk for example
    """

def init32() -> Emu: ...

def init64() -> Emu: ...

def load(filename: builtins.str) -> Emu:
    r"""
    deserialize the emulator state from a file, which can be dumped with dump
    """

def load_from_file(filename: builtins.str) -> Emu:
    r"""
    deserialize the emulator state from a file, which can be dumped with dump_to_file
    """

def load_from_minidump(filename: builtins.str) -> Emu:
    r"""
    deserialize the emulator state from a minidump file, which can be dumped with dump_to_minidump
    """

